app/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('reserva/', reserva, name="reserva"),
    path('cuenta/', cuenta, name="cuenta"),
    path('registro/', registro, name="registro"),
    path('perfil/', perfil, name="perfil"),
    path('login/', user_login, name="login"),
    path('actualizar/', editar_usuario, name="actualizar"),
    path('mascota/', mascota, name="mascota"),
    path('agregar_mascota/', agregar_mascota, name="agregar_mascota"),
    path('administracion/', administracion_view, name="administracion"),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
]

batuco/urls.py
from django.contrib import admin
from django.urls import path, include

#revisar estos imports
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
import uuid
import datetime

class CustomUserManager(BaseUserManager):
    def create_user(self, correo, nombre, rut, password=None, **extra_fields):
        if not correo:
            raise ValueError('El usuario debe tener un correo electrónico')
        correo = self.normalize_email(correo)
        user = self.model(correo=correo, nombre=nombre, rut=rut, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, correo, nombre, rut, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('El superusuario debe tener is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('El superusuario debe tener is_superuser=True.')
        return self.create_user(correo, nombre, rut, password, **extra_fields)

class TipoUsuario(models.Model):
    id_tipo_usuario = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre_tipo = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre_tipo

class Especialidad(models.Model):
    id_especialidad = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre_especialidad = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_especialidad

class Usuario(AbstractBaseUser, PermissionsMixin):
    id_usuario = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    correo = models.EmailField(unique=True)
    telefono = models.CharField(max_length=15)
    ciudad = models.CharField(max_length=50)
    comuna = models.CharField(max_length=50)
    rut = models.CharField(max_length=12, unique=True)
    tipo_permiso = models.CharField(max_length=50)
    icono = models.ImageField(upload_to='user_icons/', blank=True, null=True)
    status = models.BooleanField(default=True)

    # Foraneas
    id_tipo_usuario = models.ForeignKey(TipoUsuario, on_delete=models.SET_NULL, null=True, blank=True)
    id_especialidad = models.ForeignKey(Especialidad, on_delete=models.SET_NULL, null=True, blank=True)

    # Campos de Django
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    # Campos que generan conflicto con Django's User
    groups = models.ManyToManyField(Group, related_name='custom_user_set', blank=True)
    user_permissions = models.ManyToManyField(Permission, related_name='custom_user_permissions_set', blank=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'correo'
    REQUIRED_FIELDS = ['nombre', 'rut']

    def __str__(self):
        return self.correo

    def get_name(self):
        return self.nombre_usu

class Mascota(models.Model):
    id_mascota = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre_mascota = models.CharField(max_length=100)
    edad_mascota = models.IntegerField(null=True, blank=True)
    especie_mascota = models.CharField(max_length=100)
    raza_mascota = models.CharField(max_length=100)
    #Foranea
    id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='mascotas')

    def __str__(self):
        return self.nombre_mascota

class Tratamiento(models.Model):
    id_tratamiento = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre_tratamiento = models.CharField(max_length=100)
    costo_tratamiento = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.nombre_tratamiento

class Atencion(models.Model):
    id_atencion = models.UUIDField(primary_key=True, default=uuid.uuid4,editable=False)
    motivo_atencion = models.CharField(max_length=1000)
    fecha_atencion = models.DateField(default=datetime.date.today,null=False,blank=False)
    observacion_atencion = models.CharField(max_length=200)

    def __str__(self):
        return f"Atención: {self.motivo_atencion} - {self.fecha_atencion}"

class Ficha(models.Model):
    id_ficha = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sintomas = models.CharField(max_length=1000)
    examenes = models.CharField(max_length=200)
    observacion_ficha = models.CharField(max_length=200)

    # Foraneas
    id_atencion = models.ForeignKey(Atencion, on_delete=models.CASCADE, related_name='atencion')
    id_mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE, related_name='mascota')
    id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='usuario')
    id_tratamiento = models.ForeignKey(Tratamiento, on_delete=models.CASCADE, related_name='tratamiento')

    def __str__(self):
        return f"Ficha: {self.observacion_ficha} - {self.examenes}"

class Reserva(models.Model):
    id_reserva = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    hora_reserva = models.DateTimeField(
        default=datetime.datetime.now,
        null=False,
        blank=False,
        help_text="Fecha y hora de la reserva."
    )

    # Campo de Fecha
    fecha_reserva = models.DateField(
        default=datetime.date.today,
        null=False,
        blank=False,
        help_text="Fecha en la que se hizo la reserva."
    )

    def __str__(self):
        return f"Reserva {self.id_reserva} - {self.fecha_reserva} {self.hora_reserva}"




# formulario de contacto
opciones_consulta = [
    [0, "Consulta"],
    [1, "Reclamo"],
    [2, "Sugerencia"],
    [3, "Agradecimientos"],
]

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre

app/templates/app/actualizar.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Editar Perfil{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estilos.css' %}">
{% endblock %}

{% block contenido %}
<div class="container-fluid">
    <h2>Editar Perfil</h2>
    <form method="post" enctype="multipart/form-data" id="registroForm">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="id_direccion" class="form-label">Dirección</label>
            <input type="text" class="form-control" id="id_direccion" name="direccion" value="{{ form.direccion.value|default_if_none:'' }}" required>
            <div class="text-danger" id="direccionError"></div>
        </div>

        <div class="mb-3">
            <label for="id_comuna" class="form-label">Comuna</label>
            <input type="text" class="form-control" id="id_comuna" name="comuna" value="{{ form.comuna.value|default_if_none:'' }}" required>
            <div class="text-danger" id="comunaError"></div>
        </div>

        <div class="mb-3">
            <label for="id_ciudad" class="form-label">Ciudad</label>
            <input type="text" class="form-control" id="id_ciudad" name="ciudad" value="{{ form.ciudad.value|default_if_none:'' }}" required>
            <div class="text-danger" id="ciudadError"></div>
        </div>

        <div class="mb-3">
            <label for="id_telefono" class="form-label">Teléfono</label>
            <input type="text" class="form-control" id="id_telefono" name="telefono" value="{{ form.telefono.value|default_if_none:'' }}" required>
            <div class="text-danger" id="telefonoError"></div>
        </div>

        <div class="mb-3">
            <label for="id_icon" class="form-label">Icono</label>
            <input type="file" class="form-control" id="id_icon" name="icon" accept="image/*">
        </div>

        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-success">Guardar Cambios</button>
                <a href="{% url 'perfil' %}" class="btn btn-danger">Cancelar</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/app/administracion.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}
<div class="container mt-5">
    <div class="row">
        <button class="col-md-3 btn" onclick="toggleSection('usuarios-section')">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Usuarios</h5>
                    <p class="card-text">Gestión de usuarios</p>
                </div>
            </div>
        </button>

        <button class="col-md-3 btn" onclick="toggleSection('roles-section')">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Roles</h5>
                    <p class="card-text">Gestión de roles</p>
                </div>
            </div>
        </button>

        <button class="col-md-3 btn" onclick="toggleSection('mascotas-section')">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Mascotas</h5>
                    <p class="card-text">Gestión de mascotas</p>
                </div>
            </div>
        </button>

        <button class="col-md-3 btn" onclick="toggleSection('reservas-section')">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Reservas</h5>
                    <p class="card-text">Gestión de reservas</p>
                </div>
            </div>
        </button>
    </div>

    <div id="usuarios-section" class="mt-5" style="display:none;">
        <h3>Lista de Usuarios</h3>
        <div class="mb-3">
            <a href="{% url 'registro' %}" class="btn btn-primary">Crear Usuario</a>
        </div>
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}  <!-- Usar crispy para mostrar el formulario -->
        </form>
        <div id="usuarios-content"></div>
    </div>

    <div id="roles-section" class="mt-5" style="display:none;">
        <h3>Lista de Roles</h3>
        <div id="roles-content"></div>
    </div>

    <div id="mascotas-section" class="mt-5" style="display:none;">
        <h3>Lista de Mascotas</h3>
        <div id="mascotas-content"></div>
    </div>

    <div id="reservas-section" class="mt-5" style="display:none;">
        <h3>Lista de Reservas</h3>
        <div id="reservas-content"></div>
    </div>
</div>

<script>
    function enableSaveButton(element) {
        const row = element.closest('tr'); // Obtener la fila más cercana
        const saveButton = row.querySelector('.btn-success'); // Encontrar el botón de guardar en la fila
        if (saveButton) {
            saveButton.disabled = false; // Habilitar el botón de guardar
        }
    }

    function toggleSection(sectionId) {
        // Ocultar todas las secciones
        const sections = ['usuarios-section', 'roles-section', 'mascotas-section', 'reservas-section'];
        sections.forEach(id => {
            const section = document.getElementById(id);
            if (section) {
                section.style.display = 'none';
            }
        });

        // Mostrar la sección seleccionada
        const selectedSection = document.getElementById(sectionId);
        if (selectedSection) {
            selectedSection.style.display = 'block';
            // Cargar contenido correspondiente
            if (sectionId === 'usuarios-section') {
                loadUsuarios(); // Cargar contenido de usuarios al mostrar la sección
            } else if (sectionId === 'mascotas-section') {
                loadMascotas(); // Cargar contenido de mascotas al mostrar la sección
            }
        }
    }

    function loadUsuarios() {
        const usuarioData = {{ usuarios|safe }}; // Cargar la lista de usuarios desde el contexto de Django
        let content = `
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>ID</th>
                        <th>R.U.T</th>
                        <th>Status</th>
                        <th>Tipo de Permiso</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>`;

        usuarioData.forEach(usuario => {
            content += `
                <tr data-id="${usuario.id_usuario}">
                    <td>
                        <input type="text" class="form-control" value="${usuario.nombre}" onchange="enableSaveButton(this)">
                    </td>
                    <td>
                        <input type="text" class="form-control" value="${usuario.correo}" readonly>
                    </td>
                    <td>${usuario.id_usuario}</td>
                    <td>${usuario.rut}</td>
                    <td>${usuario.status ? 'Activo' : 'Inactivo'}</td>
                    <td>
                        <select class="form-control" onchange="enableSaveButton(this)">
                            <option value="">--</option>
                            <option value="Admin" ${usuario.tipo_permiso === 'Admin' ? 'selected' : ''}>Admin</option>
                            <option value="User" ${usuario.tipo_permiso === 'User' ? 'selected' : ''}>User</option>
                            <option value="Guest" ${usuario.tipo_permiso === 'Guest' ? 'selected' : ''}>Guest</option>
                        </select>
                    </td>
                    <td>
                        <button class="btn btn-success" onclick="saveUser('${usuario.id_usuario}')">Guardar</button>
                        <button class="btn btn-danger" onclick="deleteUser('{{ usuario.id_usuario }}')">Eliminar</button>
                    </td>
                </tr>`;
        });

        content += `
                </tbody>
            </table>`;

        document.getElementById('usuarios-content').innerHTML = content;
    }

    function loadMascotas() {
        const mascotaData = {{ mascotas|safe }}; // Cargar la lista de mascotas desde el contexto de Django
        let content = `
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre de Mascota</th>
                        <th>Edad</th>
                        <th>Especie</th>
                        <th>Raza</th>
                        <th>ID Usuario</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>`;

        mascotaData.forEach(mascota => {
            content += `
                <tr data-id="${mascota.id_mascota}">
                    <td>
                        <input type="text" class="form-control" value="${mascota.nombre_mascota}" onchange="enableSaveButton(this)">
                    </td>
                    <td>
                        <input type="number" class="form-control" value="${mascota.edad_mascota}" onchange="enableSaveButton(this)">
                    </td>
                    <td>
                        <input type="text" class="form-control" value="${mascota.especie_mascota}" onchange="enableSaveButton(this)">
                    </td>
                    <td>
                        <input type="text" class="form-control" value="${mascota.raza_mascota}" onchange="enableSaveButton(this)">
                    </td>
                    <td>${mascota.id_usuario}</td>
                    <td>
                        <button class="btn btn-success" onclick="saveMascota('${mascota.id_mascota}')">Guardar</button>
                        <button class="btn btn-danger" onclick="deleteMascota('${mascota.id_mascota}')">Eliminar</button>
                    </td>
                </tr>`;
        });

        content += `
                </tbody>
            </table>`;
        
        document.getElementById('mascotas-content').innerHTML = content;
    }

    function saveUser(userId) {
    const row = document.querySelector(`tr[data-id="${userId}"]`);
    if (!row) return;

    const nombreInput = row.querySelector('input[type="text"]');
    const correoInput = row.querySelectorAll('input[type="text"]')[1];
    const tipoPermiso = row.querySelector('select').value;

    const confirmacion = confirm("¿Estás seguro de que deseas guardar los cambios?");
    if (confirmacion) {
        const formData = new FormData();
        formData.append('action', 'update'); // Indicar la acción
        formData.append('id_usuario', userId);
        formData.append('nombre', nombreInput.value);
        formData.append('correo', correoInput.value);
        formData.append('tipo_permiso', tipoPermiso);

        fetch('/administracion/', {  
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': getCookie('csrftoken'),
            }
        })
        .then(response => {
            if (response.ok) {
                return response.text();
            } else {
                return response.text().then(text => {
                    alert('Error al actualizar el usuario: ' + text);
                });
            }
        })
        .then(data => {
            console.log('Respuesta del servidor:', data);
            // Aquí puedes manejar el HTML devuelto, si es necesario
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Error al actualizar el usuario.');
        });
    }
}

function deleteUser(userId) {
    // Confirmar si el usuario realmente quiere eliminar
    const confirmDelete = confirm('¿Estás seguro de que deseas eliminar este usuario?');
    if (confirmDelete) {
        const formData = new FormData();
        formData.append('action', 'delete'); // Indicar la acción
        formData.append('id_usuario', userId);

        fetch('/administracion/', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': getCookie('csrftoken'),
            }
        })
        .then(response => {
            if (response.ok) {
                window.location.reload(); // Recargar la página
            } else {
                return response.text().then(text => {
                    alert('Error al eliminar el usuario: ' + text);
                });
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('Error al eliminar el usuario.');
        });
    }
}





    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Si este cookie string comienza con el nombre que buscamos, obtenemos su valor
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>
{% endblock %}

app/templates/app/agregar_mascota.html
{% extends 'app/base.html' %}
{% load static %}


{% block css %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}

{% block contenido %}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <div class="card shadow" style="width: 50%;">
        <div class="card-body">
            <h2 class="card-title text-center mb-4">Registrar Nueva Mascota</h2>
            <form id="registroForm" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_nombre" class="form-label">Nombre de la Mascota</label>
                    <input type="text" class="form-control" id="id_nombre" name="nombre_mascota" required>
                    <div class="text-danger" id="nombreError"></div>
                </div>
                <div class="mb-3">
                    <label for="id_especie" class="form-label">Especie</label>
                    <input type="text" class="form-control" id="id_especie" name="especie_mascota" required>
                    <div class="text-danger" id="especieError"></div>
                </div>
                <div class="mb-3">
                    <label for="id_raza" class="form-label">Raza</label>
                    <input type="text" class="form-control" id="id_raza" name="raza_mascota" required>
                    <div class="text-danger" id="razaError"></div>
                </div>
                <div class="mb-3">
                    <label for="id_edad" class="form-label">Edad</label>
                    <input type="number" class="form-control" id="id_edad" name="edad_mascota" min="1" required>
                    <div class="text-danger" id="edadError"></div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <button type="submit" class="btn btn-primary">Guardar Mascota</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chacabuco</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/estilos.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'app/img/logo.png' %}"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'reserva' %}">Agendar cita</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Cuenta
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'perfil' %}">Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'cuenta' %}">Configurar</a></li>
                            {% if user.is_staff %}
                                <li class="nav-item">
                                    <a class="dropdown-item" href="{% url 'administracion' %}">Administración</a>
                                </li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <form action="{% url 'logout' %}" method="post" style="display:inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger">Cerrar Sesión</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}" class="nav-link">Iniciar Sesion</a>
                    </li>
                    <li>
                        <a href="{% url 'registro' %}" class="nav-link">Registrate</a>
                    </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                <div class="d-flex align-items-center ms-auto">
                    <span class="me-2">Bienvenido/a {{ user.nombre }}</span>
                </div>
                {% endif %}
            </div>
        </div>
    </nav>

    {% block contenido %}
    {% endblock %}
    <script src="{% static 'app/js/validaciones.js' %}?v=1.0.0"></script>
    <script src="{% static 'app/js/acciones.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% block contenido %}
{% load crispy_forms_tags %}
<br><br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">

                <h2>Contactanos!</h2>
                <form action=""  method="post">

                    {% csrf_token %}

                    {{ form | crispy }}

                    <input type="reset" value="Cancelar" class="btn btn-secondary">
                    <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                </form>
                {{ mensaje }}
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/app/cuenta.html
{% extends 'app/base.html' %}

{% block js %}
{% endblock %}

{% block css %}
{% endblock %}

{% block contenido %}


{% endblock %}

app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
{% endblock %}

{% block css %}
{% endblock %}

{% block contenido %}

<section>
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
        <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://cdn.pixabay.com/photo/2020/03/17/13/57/veterinary-4940425_1280.jpg" height="675px" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://cdn.pixabay.com/photo/2020/03/31/16/18/cat-4988407_1280.jpg" height="675px" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="https://cdn.pixabay.com/photo/2021/10/18/21/06/dogs-6722159_1280.jpg" height="675px" class="d-block w-100" alt="...">
        </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>

<section>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <br>
          <center>
            <img src="https://cdn.pixabay.com/photo/2020/07/17/18/16/pets-5414987_960_720.png" width="100%" alt="">
          </center>
        </div>
        <div class="col-md-6">
          <br><br><br><br>
          <h1>Acerca de nosotros</h1>
          <br>
          <h3>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsum numquam omnis dolorum culpa, tempora eligendi asperiores iusto soluta, mollitia odit modi quia nihil fugiat aspernatur libero, quod tempore nam et?</h3>
          <br>
          <a href="" class="btn btn-outline-primary">Mas Informacion</a>
        </div>
      </div>
    </div>
</section>


{% endblock %}